---
# file: jenkins.yml
# License Apache Commons v2 

#   This will confgure a jenkins vm for you.

- name: "PLAY: Configure `jenkins` vm"
  hosts: jenkins
  user: vagrant
  become: true
  vars:
    firewall_allowed_tcp_ports:
      - "22"
      - "80"
      - "8080"
  roles:
    - { role: geerlingguy.java }
    - { role: geerlingguy/jenkins }
    - { role: geerlingguy/firewall }
